---

- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Display IP Address
      debug:
        var: ansible_default_ipv4.address
    - name: Creating an empty file
      file:
        path: "/tmp/test.txt"
        state: touch
